### ISSUE TITLE
Add to starter templates and add typescript

### ISSUE THREAD

**Issue by janat08** [honojs/hono-minimal#16]
theres a list of starter templates in cloudflare docs for workers.

**Comment by janat08** [comment]
there's actually no typescript yet

**Comment by amorriscode** [comment]
There are actually [quite a few TypeScript](https://developers.cloudflare.com/workers/get-started/quickstarts/#templates) templates?

**Comment by janat08** [comment]
I meant there’s no typescript in tests while starter is advertised with ts support. A pull request can be opened that adds it to starter templates on cf guide. This is the only template with working tests.

**Comment by yusukebe** [comment]
Hi @janat08 

This starter template is already written on Cloudflare Docs.

![SS](https://user-images.githubusercontent.com/10682/168764090-0767a397-e448-4de8-bdf9-e7835f958b61.png)

**Comment by janat08** [comment]
I suppose ts testing isn't that helpful.
